interface Aria2Option {
    name: string;
    description: string | string[];
    type: string;
    readonly?: boolean;
    required?: boolean;
    defaultValue?: any;
    min?: number;
    max?: number;
    options?: string[];
    separator?: string;
    showCount?: boolean;
    overrideMode?: string;
    submitFormat?: string;
    trimCount?: boolean;
    since?: string;
    pattern?: string;
    suffix?: string;
}

export const aria2AllOptions: Record<string, Aria2Option> = {
    gid: {
        name: "gid",
        description: "Set the gid of the download.",
        type: "string",
        readonly: true,
        required: true,
    },
    dir: {
        name: "dir",
        description: "The directory to store the downloaded file.",
        type: "string",
        required: true,
    },
    log: {
        name: "log",
        description: [
            "Use log file to output log messages.",
            "The log file will be created if it does not exist.",
        ],
        type: "string",
        required: true,
    },
    "max-concurrent-downloads": {
        name: "max-concurrent-downloads",
        description: "The maximum number of downloads to run concurrently.",
        type: "number",
        defaultValue: 5,
        required: true,
        min: 1,
    },
    "check-integrity": {
        name: "check-integrity",
        description: [
            "Check file integrity by piece hashes.",
            "This option only works for BitTorrent, Metalink and HTTP/FTP downloads which have checksums.",
        ],
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    continue: {
        name: "continue",
        description: [
            "Continue downloading a partially downloaded file.",
            "If the same file is already downloaded, aria2 will skip the download.",
        ],
        type: "boolean",
        required: true,
    },
    "all-proxy": {
        name: "all-proxy",
        description: [
            "Use the specified proxy for all protocols.",
            "The format is [http://][user[:password]@]host[:port].",
        ],
        type: "string",
    },
    "all-proxy-user": {
        name: "all-proxy-user",
        description: "Set the user name for proxy authentication.",
        type: "string",
    },
    "all-proxy-passwd": {
        name: "all-proxy-passwd",
        description: "Set the password for proxy authentication.",
        type: "string",
    },
    checksum: {
        name: "checksum",
        description: "Set checksum for the file.",
        type: "string",
        required: true,
        pattern: "type=value",
    },
    "connect-timeout": {
        name: "connect-timeout",
        description:
            "Set the maximum time in seconds to wait for a connection to be established.",
        type: "number",
        suffix: "s",
        defaultValue: 60,
        required: true,
        min: 1,
    },
    "dry-run": {
        name: "dry-run",
        description: [
            "Perform a dry-run.",
            "If this option is set to true, aria2 will not download the file, but will check if the file can be downloaded.",
        ],
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "lowest-speed-limit": {
        name: "lowest-speed-limit",
        description: [
            "Close connection if the download speed is less than the specified limit.",
            "If 0 is given, this option is disabled.",
        ],
        type: "string",
        suffix: "B/s",
        defaultValue: "0",
        required: true,
        pattern: "SIZE",
    },
    "max-connection-per-server": {
        name: "max-connection-per-server",
        description: "The maximum number of connections per server.",
        type: "number",
        defaultValue: 1,
        required: true,
        min: 1,
        max: 16,
    },
    "max-file-not-found": {
        name: "max-file-not-found",
        description:
            "The maximum number of file not found errors before the download is aborted.",
        type: "number",
        defaultValue: 0,
        required: true,
        min: 0,
    },
    "max-tries": {
        name: "max-tries",
        description: "The maximum number of tries for a download.",
        type: "number",
        defaultValue: 5,
        required: true,
        min: 0,
    },
    "min-split-size": {
        name: "min-split-size",
        description: [
            "Set the minimum split size for a download.",
            "If the file size is less than this size, it will not be split.",
        ],
        type: "string",
        suffix: "B",
        defaultValue: "20M",
        required: true,
        pattern: "SIZE",
    },
    "netrc-path": {
        name: "netrc-path",
        description: "Set the path to the .netrc file.",
        type: "string",
        readonly: true,
        defaultValue: ".netrc",
    },
    "no-netrc": {
        name: "no-netrc",
        description: "Disable the use of the .netrc file.",
        type: "boolean",
        required: true,
    },
    "no-proxy": {
        name: "no-proxy",
        description: [
            "Comma-separated list of hosts or domains that should not be proxied.",
            "Example: example.com,google.com",
        ],
        type: "string",
        separator: ",",
        showCount: true,
    },
    out: {
        name: "out",
        description: [
            "Set the output file name.",
            "If the output file name is a directory, the file will be saved in that directory.",
        ],
        type: "string",
    },
    "proxy-method": {
        name: "proxy-method",
        description: "Set the proxy method.",
        type: "string",
        options: ["get", "tunnel"],
        defaultValue: "get",
        required: true,
    },
    "remote-time": {
        name: "remote-time",
        description: "Use the remote file time for the local file.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "reuse-uri": {
        name: "reuse-uri",
        description: "Reuse the URI for the download.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "retry-wait": {
        name: "retry-wait",
        description: "Set the time in seconds to wait before retrying.",
        type: "number",
        suffix: "s",
        defaultValue: 0,
        required: true,
        min: 0,
    },
    "server-stat-of": {
        name: "server-stat-of",
        description: "Set the file for server statistics.",
        type: "string",
    },
    "server-stat-timeout": {
        name: "server-stat-timeout",
        description: "Set the timeout in seconds for server statistics.",
        type: "number",
        suffix: "s",
        readonly: true,
        defaultValue: 60,
    },
    split: {
        name: "split",
        description: "Set the number of splits for a download.",
        type: "number",
        defaultValue: 5,
        required: true,
        min: 1,
    },
    "stream-piece-selector": {
        name: "stream-piece-selector",
        description: "Set the selector for streaming pieces.",
        type: "string",
        options: ["default", "inorder", "geom", "random"],
        defaultValue: "default",
        required: true,
    },
    timeout: {
        name: "timeout",
        description: "Set the timeout in seconds for the download.",
        type: "number",
        suffix: "s",
        defaultValue: 60,
        required: true,
        min: 1,
    },
    "uri-selector": {
        name: "uri-selector",
        description: "Set the selector for URIs.",
        type: "string",
        options: ["feedback", "inorder", "random"],
        defaultValue: "feedback",
        required: true,
    },
    "check-certificate": {
        name: "check-certificate",
        description: "Check SSL/TLS certificate.",
        type: "boolean",
        readonly: true,
        defaultValue: true,
    },
    "http-accept-gzip": {
        name: "http-accept-gzip",
        description: "Accept gzip encoded content.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "http-auth-challenge": {
        name: "http-auth-challenge",
        description: "Enable HTTP authentication challenge.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "http-no-cache": {
        name: "http-no-cache",
        description: "Disable HTTP caching.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "http-user": {
        name: "http-user",
        description: "Set the user name for HTTP authentication.",
        type: "string",
    },
    "http-passwd": {
        name: "http-passwd",
        description: "Set the password for HTTP authentication.",
        type: "string",
    },
    "http-proxy": {
        name: "http-proxy",
        description: "Set the proxy for HTTP.",
        type: "string",
    },
    "http-proxy-user": {
        name: "http-proxy-user",
        description: "Set the user name for HTTP proxy authentication.",
        type: "string",
    },
    "http-proxy-passwd": {
        name: "http-proxy-passwd",
        description: "Set the password for HTTP proxy authentication.",
        type: "string",
    },
    "https-proxy": {
        name: "https-proxy",
        description: "Set the proxy for HTTPS.",
        type: "string",
    },
    "https-proxy-user": {
        name: "https-proxy-user",
        description: "Set the user name for HTTPS proxy authentication.",
        type: "string",
    },
    "https-proxy-passwd": {
        name: "https-proxy-passwd",
        description: "Set the password for HTTPS proxy authentication.",
        type: "string",
    },
    referer: {
        name: "referer",
        description: "Set the referer for the HTTP request.",
        type: "string",
    },
    "enable-http-keep-alive": {
        name: "enable-http-keep-alive",
        description: "Enable HTTP keep-alive.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "enable-http-pipelining": {
        name: "enable-http-pipelining",
        description: "Enable HTTP pipelining.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    header: {
        name: "header",
        description: "Set the HTTP header.",
        type: "string",
        separator: "\\n",
        overrideMode: "overwrite",
        submitFormat: "header",
        showCount: true,
        trimCount: true,
    },
    "save-cookies": {
        name: "save-cookies",
        description: "Save cookies to a file.",
        type: "string",
    },
    "use-head": {
        name: "use-head",
        description: "Use HTTP HEAD method.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "user-agent": {
        name: "user-agent",
        description: "Set the user agent for the HTTP request.",
        type: "string",
        defaultValue: "aria2/1.x.x",
    },
    "ftp-user": {
        name: "ftp-user",
        description: "Set the user name for FTP authentication.",
        type: "string",
        defaultValue: "anonymous",
    },
    "ftp-passwd": {
        name: "ftp-passwd",
        description: "Set the password for FTP authentication.",
        type: "string",
        defaultValue: "anonymous@aria2",
    },
    "ftp-pasv": {
        name: "ftp-pasv",
        description: "Enable passive mode for FTP.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "ftp-proxy": {
        name: "ftp-proxy",
        description: "Set the proxy for FTP.",
        type: "string",
    },
    "ftp-proxy-user": {
        name: "ftp-proxy-user",
        description: "Set the user name for FTP proxy authentication.",
        type: "string",
    },
    "ftp-proxy-passwd": {
        name: "ftp-proxy-passwd",
        description: "Set the password for FTP proxy authentication.",
        type: "string",
    },
    "ftp-type": {
        name: "ftp-type",
        description: "Set the FTP transfer type.",
        type: "string",
        options: ["binary", "ascii"],
        defaultValue: "binary",
        required: true,
    },
    "ftp-reuse-connection": {
        name: "ftp-reuse-connection",
        description: "Reuse the FTP connection.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "ssh-host-key-md": {
        name: "ssh-host-key-md",
        description: "Set the SSH host key MD5/SHA1 fingerprint.",
        type: "string",
    },
    "show-files": {
        name: "show-files",
        description: "Show files in the torrent.",
        type: "boolean",
        readonly: true,
    },
    "bt-detach-seed-only": {
        name: "bt-detach-seed-only",
        description: "Detach after seeding is finished.",
        type: "boolean",
        readonly: true,
        defaultValue: false,
    },
    "bt-enable-hook-after-hash-check": {
        name: "bt-enable-hook-after-hash-check",
        description: "Enable hook after hash check.",
        type: "boolean",
        defaultValue: true,
        required: true,
        since: "1.16.0",
    },
    "bt-enable-lpd": {
        name: "bt-enable-lpd",
        description: "Enable Local Peer Discovery.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "bt-exclude-tracker": {
        name: "bt-exclude-tracker",
        description: "Comma-separated list of tracker addresses to exclude.",
        type: "string",
        separator: ",",
        showCount: true,
    },
    "bt-external-ip": {
        name: "bt-external-ip",
        description: "Set the external IP address.",
        type: "string",
    },
    "bt-force-encryption": {
        name: "bt-force-encryption",
        description: "Force BitTorrent encryption.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "bt-hash-check-seed": {
        name: "bt-hash-check-seed",
        description: "Check hash and seed.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "bt-load-saved-metadata": {
        name: "bt-load-saved-metadata",
        description: "Load saved metadata.",
        type: "boolean",
        defaultValue: false,
        required: true,
        since: "1.16.0",
    },
    "bt-max-open-files": {
        name: "bt-max-open-files",
        description: "The maximum number of open files.",
        type: "number",
        defaultValue: 100,
        required: true,
        min: 1,
    },
    "bt-max-peers": {
        name: "bt-max-peers",
        description: "The maximum number of peers.",
        type: "number",
        defaultValue: 55,
        required: true,
        min: 1,
    },
    "bt-metadata-only": {
        name: "bt-metadata-only",
        description: "Only download metadata.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "bt-min-crypto-level": {
        name: "bt-min-crypto-level",
        description: "Set the minimum encryption level.",
        type: "string",
        options: ["plain", "arc4"],
        defaultValue: "plain",
        required: true,
    },
    "bt-prioritize-piece": {
        name: "bt-prioritize-piece",
        description: "Prioritize pieces.",
        type: "string",
    },
    "bt-remove-unselected-file": {
        name: "bt-remove-unselected-file",
        description: "Remove unselected files.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "bt-require-crypto": {
        name: "bt-require-crypto",
        description: "Require BitTorrent encryption.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "bt-request-peer-speed-limit": {
        name: "bt-request-peer-speed-limit",
        description: "Set the speed limit for peer requests.",
        type: "string",
        suffix: "B/s",
        defaultValue: "50K",
        required: true,
        pattern: "SIZE",
    },
    "bt-save-metadata": {
        name: "bt-save-metadata",
        description: "Save BitTorrent metadata.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "bt-seed-unverified": {
        name: "bt-seed-unverified",
        description: "Seed unverified files.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "bt-stop-timeout": {
        name: "bt-stop-timeout",
        description: "Set the timeout in seconds for stopping BitTorrent.",
        type: "number",
        suffix: "s",
        defaultValue: 0,
        required: true,
        min: 0,
    },
    "bt-tracker": {
        name: "bt-tracker",
        description: "Comma-separated list of tracker addresses.",
        type: "string",
        separator: ",",
        showCount: true,
    },
    "bt-tracker-connect-timeout": {
        name: "bt-tracker-connect-timeout",
        description: "Set the tracker connection timeout.",
        type: "number",
        suffix: "s",
        defaultValue: 60,
        required: true,
        min: 1,
    },
    "bt-tracker-interval": {
        name: "bt-tracker-interval",
        description: "Set the tracker interval.",
        type: "number",
        suffix: "s",
        defaultValue: 0,
        required: true,
        min: 0,
    },
    "bt-tracker-timeout": {
        name: "bt-tracker-timeout",
        description: "Set the tracker timeout.",
        type: "number",
        suffix: "s",
        defaultValue: 60,
        required: true,
        min: 1,
    },
    "dht-file-path": {
        name: "dht-file-path",
        description: "Set the DHT file path.",
        type: "string",
        readonly: true,
    },
    "dht-file-path6": {
        name: "dht-file-path6",
        description: "Set the DHT IPv6 file path.",
        type: "string",
        readonly: true,
    },
    "dht-listen-port": {
        name: "dht-listen-port",
        description: "Set the DHT listen port.",
        type: "number",
        readonly: true,
    },
    "dht-message-timeout": {
        name: "dht-message-timeout",
        description: "Set the DHT message timeout.",
        type: "number",
        suffix: "s",
        readonly: true,
    },
    "enable-dht": {
        name: "enable-dht",
        description: "Enable DHT.",
        type: "boolean",
        readonly: true,
    },
    "enable-dht6": {
        name: "enable-dht6",
        description: "Enable DHT IPv6.",
        type: "boolean",
        readonly: true,
    },
    "enable-peer-exchange": {
        name: "enable-peer-exchange",
        description: "Enable peer exchange.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "follow-torrent": {
        name: "follow-torrent",
        description: "Follow torrent.",
        type: "string",
        options: ["true", "false", "mem"],
        defaultValue: "true",
        required: true,
    },
    "listen-port": {
        name: "listen-port",
        description: "Set the listen port.",
        type: "number",
        readonly: true,
    },
    "max-overall-upload-limit": {
        name: "max-overall-upload-limit",
        description: "Set the maximum overall upload limit.",
        type: "string",
        suffix: "B/s",
        defaultValue: "0",
        required: true,
        pattern: "SIZE",
    },
    "max-upload-limit": {
        name: "max-upload-limit",
        description: "Set the maximum upload limit.",
        type: "string",
        suffix: "B/s",
        defaultValue: "0",
        required: true,
        pattern: "SIZE",
    },
    "peer-id-prefix": {
        name: "peer-id-prefix",
        description: "Set the peer ID prefix.",
        type: "string",
        readonly: true,
    },
    "peer-agent": {
        name: "peer-agent",
        description: "Set the peer agent.",
        type: "string",
        readonly: true,
        since: "1.16.0",
    },
    "seed-ratio": {
        name: "seed-ratio",
        description: "Set the seed ratio.",
        type: "number",
        defaultValue: 1.0,
        required: true,
        min: 0,
    },
    "seed-time": {
        name: "seed-time",
        description: "Set the seed time.",
        type: "number",
        suffix: "m",
        required: true,
        min: 0,
    },
    "follow-metalink": {
        name: "follow-metalink",
        description: "Follow metalink.",
        type: "string",
        options: ["true", "false", "mem"],
        defaultValue: "true",
        required: true,
    },
    "metalink-base-uri": {
        name: "metalink-base-uri",
        description: "Set the metalink base URI.",
        type: "string",
    },
    "metalink-language": {
        name: "metalink-language",
        description: "Set the metalink language.",
        type: "string",
    },
    "metalink-location": {
        name: "metalink-location",
        description: "Set the metalink location.",
        type: "string",
    },
    "metalink-os": {
        name: "metalink-os",
        description: "Set the metalink OS.",
        type: "string",
    },
    "metalink-version": {
        name: "metalink-version",
        description: "Set the metalink version.",
        type: "string",
    },
    "metalink-preferred-protocol": {
        name: "metalink-preferred-protocol",
        description: "Set the preferred protocol for metalink.",
        type: "string",
        options: ["http", "https", "ftp"],
        defaultValue: "http",
        required: true,
    },
    "metalink-enable-unique-protocol": {
        name: "metalink-enable-unique-protocol",
        description: "Enable unique protocol for metalink.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "enable-rpc": {
        name: "enable-rpc",
        description: "Enable RPC.",
        type: "boolean",
        readonly: true,
    },
    "pause-metadata": {
        name: "pause-metadata",
        description: "Pause metadata.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "rpc-allow-origin-all": {
        name: "rpc-allow-origin-all",
        description: "Allow all origins for RPC.",
        type: "boolean",
        readonly: true,
    },
    "rpc-listen-all": {
        name: "rpc-listen-all",
        description: "Listen all for RPC.",
        type: "boolean",
        readonly: true,
    },
    "rpc-listen-port": {
        name: "rpc-listen-port",
        description: "Set the RPC listen port.",
        type: "number",
        readonly: true,
    },
    "rpc-max-request-size": {
        name: "rpc-max-request-size",
        description: "Set the maximum request size for RPC.",
        type: "number",
        suffix: "M",
        readonly: true,
    },
    "rpc-save-upload-metadata": {
        name: "rpc-save-upload-metadata",
        description: "Save upload metadata for RPC.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "rpc-secure": {
        name: "rpc-secure",
        description: "Enable RPC secure.",
        type: "boolean",
        readonly: true,
    },
    "allow-overwrite": {
        name: "allow-overwrite",
        description: "Allow overwrite.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "allow-piece-length-change": {
        name: "allow-piece-length-change",
        description: "Allow piece length change.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "always-resume": {
        name: "always-resume",
        description: "Always resume.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "async-dns": {
        name: "async-dns",
        description: "Enable async DNS.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "auto-file-renaming": {
        name: "auto-file-renaming",
        description: "Enable auto file renaming.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "auto-save-interval": {
        name: "auto-save-interval",
        description: "Set the auto save interval.",
        type: "number",
        suffix: "s",
        readonly: true,
    },
    "conditional-get": {
        name: "conditional-get",
        description: "Enable conditional GET.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "conf-path": {
        name: "conf-path",
        description: "Set the configuration file path.",
        type: "string",
        readonly: true,
    },
    "console-log-level": {
        name: "console-log-level",
        description: "Set the console log level.",
        type: "string",
        options: ["debug", "info", "notice", "warn", "error"],
        readonly: true,
    },
    "content-disposition-default-utf8": {
        name: "content-disposition-default-utf8",
        description: "Set the content disposition default UTF-8.",
        type: "boolean",
        defaultValue: false,
        since: "1.14.0",
    },
    daemon: {
        name: "daemon",
        description: "Run as daemon.",
        type: "boolean",
        readonly: true,
    },
    "deferred-input": {
        name: "deferred-input",
        description: "Enable deferred input.",
        type: "boolean",
        readonly: true,
    },
    "disable-ipv6": {
        name: "disable-ipv6",
        description: "Disable IPv6.",
        type: "boolean",
        readonly: true,
    },
    "disk-cache": {
        name: "disk-cache",
        description: "Set the disk cache.",
        type: "number",
        suffix: "M",
        readonly: true,
    },
    "download-result": {
        name: "download-result",
        description: "Set the download result.",
        type: "string",
        options: ["full", "hidden"],
        defaultValue: "full",
        required: true,
    },
    dscp: {
        name: "dscp",
        description: "Set the DSCP.",
        type: "number",
        readonly: true,
    },
    "rlimit-nofile": {
        name: "rlimit-nofile",
        description: "Set the limit for open files.",
        type: "number",
        readonly: true,
    },
    "enable-color": {
        name: "enable-color",
        description: "Enable color.",
        type: "boolean",
        readonly: true,
    },
    "enable-mmap": {
        name: "enable-mmap",
        description: "Enable mmap.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "event-poll": {
        name: "event-poll",
        description: "Set the event poll method.",
        type: "string",
        options: ["epoll", "poll", "select"],
        readonly: true,
    },
    "file-allocation": {
        name: "file-allocation",
        description: "Set the file allocation method.",
        type: "string",
        options: ["none", "prealloc", "trunc", "falloc"],
        defaultValue: "prealloc",
        required: true,
    },
    "force-save": {
        name: "force-save",
        description: "Force save.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "save-not-found": {
        name: "save-not-found",
        description: "Save not found.",
        type: "boolean",
        defaultValue: false,
        required: true,
        since: "1.16.2",
    },
    "hash-check-only": {
        name: "hash-check-only",
        description: "Check hash only.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    "human-readable": {
        name: "human-readable",
        description: "Enable human readable.",
        type: "boolean",
        readonly: true,
    },
    "keep-unfinished-download-result": {
        name: "keep-unfinished-download-result",
        description: "Keep unfinished download result.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "max-download-result": {
        name: "max-download-result",
        description: "Set the maximum download result.",
        type: "number",
        defaultValue: 1000,
        required: true,
        min: 0,
    },
    "max-mmap-limit": {
        name: "max-mmap-limit",
        description: "Set the maximum mmap limit.",
        type: "string",
        suffix: "B",
        defaultValue: "9223372036854775807",
        required: true,
        pattern: "SIZE",
        since: "1.16.0",
    },
    "max-resume-failure-tries": {
        name: "max-resume-failure-tries",
        description: "Set the maximum resume failure tries.",
        type: "number",
        defaultValue: 0,
        required: true,
        min: 0,
    },
    "min-tls-version": {
        name: "min-tls-version",
        description: "Set the minimum TLS version.",
        type: "string",
        options: ["TLSv1", "TLSv1.1", "TLSv1.2"],
        readonly: true,
    },
    "log-level": {
        name: "log-level",
        description: "Set the log level.",
        type: "string",
        options: ["debug", "info", "notice", "warn", "error"],
        defaultValue: "debug",
        required: true,
    },
    "optimize-concurrent-downloads": {
        name: "optimize-concurrent-downloads",
        description: "Optimize concurrent downloads.",
        type: "boolean",
        defaultValue: false,
        since: "1.16.0",
    },
    "piece-length": {
        name: "piece-length",
        description: "Set the piece length.",
        type: "string",
        suffix: "B",
        defaultValue: "1M",
        required: true,
        pattern: "SIZE",
    },
    "show-console-readout": {
        name: "show-console-readout",
        description: "Show console readout.",
        type: "boolean",
        readonly: true,
    },
    "summary-interval": {
        name: "summary-interval",
        description: "Set the summary interval.",
        type: "number",
        suffix: "s",
        readonly: true,
    },
    "max-overall-download-limit": {
        name: "max-overall-download-limit",
        description: "Set the maximum overall download limit.",
        type: "string",
        suffix: "B/s",
        defaultValue: "0",
        required: true,
        pattern: "SIZE",
    },
    "max-download-limit": {
        name: "max-download-limit",
        description: "Set the maximum download limit.",
        type: "string",
        suffix: "B/s",
        defaultValue: "0",
        required: true,
        pattern: "SIZE",
    },
    "no-conf": {
        name: "no-conf",
        description: "Disable configuration file.",
        type: "boolean",
        readonly: true,
    },
    "no-file-allocation-limit": {
        name: "no-file-allocation-limit",
        description: "Set the no file allocation limit.",
        type: "string",
        suffix: "B",
        defaultValue: "5M",
        required: true,
        pattern: "SIZE",
    },
    "parameterized-uri": {
        name: "parameterized-uri",
        description: "Enable parameterized URI.",
        type: "boolean",
        defaultValue: false,
        required: true,
    },
    quiet: {
        name: "quiet",
        description: "Quiet mode.",
        type: "boolean",
        readonly: true,
    },
    "realtime-chunk-checksum": {
        name: "realtime-chunk-checksum",
        description: "Enable realtime chunk checksum.",
        type: "boolean",
        defaultValue: true,
        required: true,
    },
    "remove-control-file": {
        name: "remove-control-file",
        description: "Remove control file.",
        type: "boolean",
        required: true,
    },
    "save-session": {
        name: "save-session",
        description: "Save session to a file.",
        type: "string",
    },
    "save-session-interval": {
        name: "save-session-interval",
        description: "Set the save session interval.",
        type: "number",
        suffix: "s",
        readonly: true,
    },
    "socket-recv-buffer-size": {
        name: "socket-recv-buffer-size",
        description: "Set the socket receive buffer size.",
        type: "number",
        suffix: "B",
        readonly: true,
        since: "1.16.0",
    },
    stop: {
        name: "stop",
        description: "Stop after the download.",
        type: "number",
        suffix: "s",
        readonly: true,
    },
    "truncate-console-readout": {
        name: "truncate-console-readout",
        description: "Truncate console readout.",
        type: "boolean",
        readonly: true,
    },
};
