export const taskOptions = [
    { key: 'dir', category: 'global', canUpdate: 'new', showHistory: true },
    { key: 'out', category: 'http', canUpdate: 'new' },
    { key: 'allow-overwrite', category: 'global', canShow: 'new' },
    { key: 'max-download-limit', category: 'global' },
    { key: 'max-upload-limit', category: 'bittorrent' },
    { key: 'split', category: 'http', canUpdate: 'new|waiting|paused' },
    { key: 'min-split-size', category: 'http', canUpdate: 'new|waiting|paused' },
    { key: 'max-connection-per-server', category: 'http', canUpdate: 'new|waiting|paused' },
    { key: 'lowest-speed-limit', category: 'http', canUpdate: 'new|waiting|paused' },
    { key: 'stream-piece-selector', category: 'http', canUpdate: 'new|waiting|paused' },
    { key: 'http-user', category: 'http', canUpdate: 'new|waiting|paused' },
    { key: 'http-passwd', category: 'http', canUpdate: 'new|waiting|paused' },
    { key: 'all-proxy', category: 'http', canUpdate: 'new|waiting|paused' },
    { key: 'all-proxy-user', category: 'http', canUpdate: 'new|waiting|paused' },
    { key: 'all-proxy-passwd', category: 'http', canUpdate: 'new|waiting|paused' },
    { key: 'checksum', category: 'http' },
    { key: 'continue', category: 'http', canUpdate: 'new|waiting|paused' },
    { key: 'referer', category: 'http', canUpdate: 'new' },
    { key: 'header', category: 'http', canUpdate: 'new' },
    { key: 'bt-max-peers', category: 'bittorrent' },
    { key: 'bt-request-peer-speed-limit', category: 'bittorrent' },
    { key: 'bt-remove-unselected-file', category: 'bittorrent' },
    { key: 'bt-stop-timeout', category: 'bittorrent', canUpdate: 'new|waiting|paused' },
    { key: 'bt-tracker', category: 'bittorrent', canUpdate: 'new|waiting|paused' },
    { key: 'seed-ratio', category: 'bittorrent', canUpdate: 'new|waiting|paused' },
    { key: 'seed-time', category: 'bittorrent', canUpdate: 'new|waiting|paused' },
    { key: 'pause-metadata', category: 'bittorrent', canUpdate: 'new' },
    { key: 'conditional-get', category: 'global', canShow: 'new' },
    { key: 'check-integrity', category: 'global' },
    { key: 'file-allocation', category: 'global', canShow: 'new' },
    { key: 'parameterized-uri', category: 'global', canShow: 'new' },
    { key: 'force-save', category: 'global' }
];
